### ISSUE TITLE
Diseño Visual Studio

### ISSUE THREAD

**Issue by mariagfh1228** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipo-topicos-avanzados#1]
[Reporte Practica 2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-equipo-topicos-avanzados/files/10756622/Reporte.Practica.2.pdf)

**Comment by Julissamigdalia** [comment]
Faltaron más fotografías y describir resultados 
18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
